### ISSUE TITLE
Baking NavMesh with 2D colliders?

### ISSUE THREAD

**Issue by Wokarol** [Unity-Technologies/NavMeshComponents#102]
Any idea how to do it? Because using 3D colliders just for NavMesh seems useless and ineffective.

**Comment by laurentopia** [comment]
Try this https://github.com/h8man/NavMeshPlus

**Comment by Wokarol** [comment]
I'm using my own solution right now. I've made a script that makes 3D Colliders in the place of 2D Colliders for the time of baking

**Comment by laurentopia** [comment]
does it work with tilemaps?

**Comment by Wokarol** [comment]
No, my solution works with circle, box and capsule colliders 2D

**Comment by Wokarol** [comment]
I'll try to do Polygon Collider 2D soon, however I don't know how to approach Tilemap Collider because I don't have any idea how to get any data about shape of it.

**Comment by laurentopia** [comment]
Add a CompositeCollider2D and use https://docs.unity3d.com/ScriptReference/CompositeCollider2D.GetPath.html

**Comment by Wokarol** [comment]
I've made this like that and it works quite well. I only need to add support for polygon and edge collider

**Comment by Wokarol** [comment]
I've found a way to convert convex collider and edge collider to 3D colliders (edge radius was tricky). I'll upload it on GitHub and post link here when it will be fully done.

**Comment by laurentopia** [comment]
Thanks for sharing, in 18.2 it's not compiling.

**Comment by Wokarol** [comment]
Strange, can I know what's the error message?

**Comment by Wokarol** [comment]
I might know the issue, maybe try switching to .NET 4.x

**Comment by laurentopia** [comment]
it's in 4.x
`Assets/NavMeshComponents/Scripts/NavMeshSurface.cs(16,6): error CS0246: The type or namespace name `ExecuteAlways' could not be found. Are you missing an assembly reference?`

**Comment by Wokarol** [comment]
Strange, have you tried importing NavMeshComponents on you own and import only 2DNavMeshBaking from my package? Maybe I forgot about something

**Comment by laurentopia** [comment]
I just did that.
All component errors are gone but now I get

> Assets/Scripts/NavMeshComponents/Editor/NavMeshAssetManager.cs(268,46): error CS0246: The type or namespace name `PrefabStage' could not be found. Are you missing an assembly reference?

> Assets/Scripts/NavMeshComponents/Editor/NavMeshAssetManager.cs(3,32): error CS0234: The type or namespace name `SceneManagement' does not exist in the namespace `UnityEditor.Experimental'. Are you missing an assembly reference?

**Comment by Wokarol** [comment]
I'll check this later this day.

**Comment by Wokarol** [comment]
@laurentopia // I know where is the problem. It works on 2018.3 and It doesn't work on 2018.2. I grabbed NavMeshComponents for Unity 2018.3 (that's what I'm using in my current project). Here, take a package with correct NavMeshComponents version https://github.com/Wokarol/NavMesh2D/releases/tag/v1.0.1-2018.2

**Comment by laurentopia** [comment]
Cheers!
So what type of colliders do I need to put on my tilemaps?
I have tilemapcollider with composite on/off
composite in edge or poly
neither show up in the navmesh

**Comment by Wokarol** [comment]
You should be able to use edge collider, composite collider, polygon collider, box collider, circle collider, capsule collider. All are supported.
Make sure that you have newest version

**Comment by laurentopia** [comment]
I'm doing it wrong then - what are the steps?

**Comment by Wokarol** [comment]
You should add 2D Baker to object rotated to -90 degrees on x, and... that's all

**Comment by Wokarol** [comment]
You need to press "Bake 2D" button (or something alongside those lines)

**Comment by laurentopia** [comment]
even with a square 2d collider it doesn't show anything

**Comment by Wokarol** [comment]
Hmmm... you have your colliders set to static?

**Comment by laurentopia** [comment]
bingo!
I wasn't doing static because I need a dynamic world.

**Comment by laurentopia** [comment]
navmesh modifier are ignored

**Comment by Wokarol** [comment]
Navmesh modifier? What do mean by that?

**Comment by laurentopia** [comment]
https://docs.unity3d.com/Manual/class-NavMeshModifier.html

**Comment by laurentopia** [comment]
oh and here is something interesting:
![image](https://user-images.githubusercontent.com/26075468/48584293-2c64fe00-e8de-11e8-9fe1-be6972ba9007.png)
on composite tilemap collider like this
![image](https://user-images.githubusercontent.com/26075468/48584305-3be44700-e8de-11e8-8c59-dd02298c3090.png)

**Comment by Wokarol** [comment]
I haven't looked into that yet, but they should work like for 3D nav mesh

**Comment by laurentopia** [comment]
so how do you do it? and can this bake at runtime, and update regions?

**Comment by Wokarol** [comment]
From the technical point of view it is 3D Nav Mesh and I'm just creating childs of 2D Colliders with "3D representations"

**Comment by laurentopia** [comment]
so you fit a cube in a square2d, a sphere in a cicle2D etc,,, ?

**Comment by Wokarol** [comment]
You can see how it's working by commenting line 40 (with DestroyImmediate(createdObject);) in NavMesh2DBaker.cs

**Comment by Wokarol** [comment]
(You'll need to find and delete every object with "_NMClone" in name)

**Comment by Wokarol** [comment]
And NavMeshGround object

**Comment by Wokarol** [comment]
I'm not using spheres but capsules, because with spheres there were slopes

**Comment by Wokarol** [comment]
I've noticed that unity leaves those holes inside geometry, not a big deal. My advice is to set NavMeshSurface to volume with dimensions of (something, 2, something) or close to that

**Comment by Wokarol** [comment]
I mean set a "Collect objects" field in NavMeshSurface to "Volume" and set size to same x as in NavMesh2DBaker, z same as y in NavMesh2DBaker and y set to 2

**Comment by Wokarol** [comment]
That way it wont pick up "tops" of the colliders

**Comment by laurentopia** [comment]
here is a better way:
carry over the modifier from the 2D collider:
![image](https://user-images.githubusercontent.com/26075468/48588364-b23b7600-e8eb-11e8-9d45-dabb62099685.png)

**Comment by Wokarol** [comment]
It should do the job, but all generated 3D colliders should be on the same z plane as NavMesh so setting NavMeshSurface volume just works globally

**Comment by Wokarol** [comment]
NavMeshVolume works, and NavMeshModifiers works when you're using 3D colliders for them

**Comment by laurentopia** [comment]
I'm trying out Astar 2D, it bakes very fast but the pathing is odd at time...
If this doesn't work I'll just give up tilemap and do sprite prefab with 3D colliders, like everybody else...
